### ISSUE TITLE
SDG Labeling of every project

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#102]
Tools like https://github.com/osdg-ai/osdg-tool would allow us to label every project based on a SDG. As input the README, documentation or website could be used. 
@SimonasTr @lukas-pkl: Are you interested in joining this effort?

**Comment by lukas-pkl** [comment]
Hey!

Sure - sounds interesting. What input from us would you need?
We have an API for the text labeling, maybe you could use that to label the projects.

**Comment by Ly0n** [comment]
We already labeled the projects by sorting them into rubrics and extracted even more topic data via the GitHub API. You can find the data we already extracted here: https://airtable.com/shr9we419r2TkpLkc
In the future, it would also be conceivable to obtain DOI and scientific publications from the projects. Maybe this is interesting for the osdg-tool to improve the NLP behind it. 

The whole thing is part of a study we're working on right now: https://opensustain.tech/blog/impact_and_potential_of_open_source_on_climate_technology/  

Perhaps there will be an opportunity to work together on this study.

**Comment by lukas-pkl** [comment]
Looks interesting!

We try to help out with projects like this any way can. Please tell us more about how we can be of help. Maybe we could arrange a call to discuss this further?

**Comment by Ly0n** [comment]
What about next week? I usually work on the project in the morning and am relatively flexible during that time. You can contact me here: tobias.augspurger@protontypes.eu

**Comment by lukas-pkl** [comment]
Great I have sent you an invite.
