### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [protontypes/open-sustainable-technology#131]
Hi, I found some broken links:

- [ ] https://github.com/ecmwf-projects/copernicus-training (file: education.md, status code: 404)
- [ ] https://carbonmapperdata.org/ (file: README.md, error: ECONNRESET)
- [ ] https://github.com/fineprint-global/forbio (file: README.md, status code: 404)
- [ ] https://forge.ipsl.jussieu.fr/nemo/wiki/Users (file: README.md, status code: 404)
- [ ] https://git.outils-is.ird.fr/grelet/TSG-QC (file: README.md, error: ENOTFOUND)
- [ ] https://juliaclimate.github.io/GlobalOceanNotebooks/ (file: README.md, status code: 404)
- [ ] https://ts-gitlab.iup.uni-heidelberg.de/dorie/dorie (file: README.md, status code: 404)
- [ ] https://bitbucket.org/anyelacamargo/aquacropr/ (file: README.md, status code: 404)
- [ ] https://github.com/FZJ-IEK2-VSA/HIM (file: docs/blog/gathering_open_sustainable_technology.md, status code: 404)
- [ ] https://protontypes.eu/about_free_innovation/ (file: docs/blog/gathering_open_sustainable_technology.md, status code: 404)
- [ ] https://https://www.weforum.org/agenda/2021/12/natural-climate-solutions-carbon-markets-climate-justice/ (file: docs/blog/impact_and_potential_of_open_source_on_climate_technology.md, error: ENOTFOUND)
- [ ] https://https://chaoss.community/metrics/ (file: docs/blog/impact_and_potential_of_open_source_on_climate_technology.md, error: ENOTFOUND)

**Comment by Ly0n** [comment]
Thank you so much. I will have a deeper look into the links today. What tool have you used to find them?

**Comment by ndsvw** [comment]
No problem.

I used https://github.com/tcort/markdown-link-check

**Comment by Ly0n** [comment]
Thanks again! I was able to save some of the links.
