### ISSUE TITLE
Apply for InvestInOpen Grant

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#137]
A grant would be helpful for further reports and further work on the website. This could also help to finance travel expenses and workshops. 

@rockita has proposed to apply for one grant with the next deadline at the end of the month:
https://investinopen.org/

**Comment by jmertic** [comment]
@dbrownlf should be involved here.

**Comment by dbrownlf** [comment]
I'm happy to help here! Have you already started on the application materials @Ly0n ?

**Comment by Ly0n** [comment]
Thanks @dbrownlf for the support! Unfortunately I haven't had a chance to work on the issue yet, but I hope to find the time this weekend. Maybe you find the time on Monday to review it. We should collect somewhere the applications so that we can reused parts of it. 

In the past I have tried to apply for a lot of these funds. The problem is that what we are doing is very unique and most people do not understand the value. The whole ecosystem analytics itself it pretty new. 

So I don't think the chances are very high that we'll get one of them. Maybe thanks to the report and the fact that LF Energy is supporting. In this way people see the value that other organisations see.  For the infrastructure funds we are not software enough and for the data funds we are to much software. 

Here a list of possible funds:
- https://subak.org/ :heavy_check_mark: (@rockita  was financed for one year)
- https://scoss.org/
- https://investinopen.org/blog/open-infrastructure-fund-pilot-cfp/#advisory-panel
- https://prototypefund.de/ ❌ ❌ ❌
- https://sovereigntechfund.de/en/ 
- https://github.com/PlaintextGroup/oss-virtual-incubator ❌

I applied for many more in the past when the projects was at the beginning.

**Comment by Ly0n** [comment]
@dbrownlf I wrote the application for InvestInOpen today. The deadline is tomorrow evening. 
I just applied for $2500 to cover the traveling cost of 5 community members traveling to conference and community meetings. 

Here the application:
https://hackmd.io/hmTXKAamTjOgOdTYvqM8Qw

Any feedback is welcome. ( I had not much time to write this )

**Comment by dbrownlf** [comment]
@Ly0n Looks good! I made a few small tweaks just for clarity and language. You can go ahead and submit this.

**Comment by Ly0n** [comment]
Thank you so much @dbrownlf! I would be surprised if we get this grant since 60% of the total volume goes to low income developers but let's see.
