### ISSUE TITLE
Creation of an blog post to announce the next report 

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#146]
For the next report we need a announcement blog post. This helps us to find more contributors to the database but also to the report. In this way, we can also agree on a common alignment for the report in advance. The announcement blog post on the first report can be found here:
https://opensustain.tech/blog/impact_and_potential_of_open_source_on_climate_technology/

**Comment by dbrownlf** [comment]
I'd like to tie this into an announcement of becoming a formal LF Energy project. We can do a broader media campaign in addition to the blog post.
