### ISSUE TITLE
Apply as an official LF Energy project 

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#147]
OpenSustain.tech needs more partners to grow and sustain the project in the long term. LF Energy can also help build a neutral govermance structure. Additionally, there are a lot of synergies with LF Energy and a lot of interesting people at LF who want to help to develop OpenSustain.tech further.

**Comment by jmertic** [comment]
I can help here :)

**Comment by Ly0n** [comment]
I have gone through the documents for the [LF Energy project proposal](https://wiki.lfenergy.org/display/HOME/LF+Energy+Guiding+Principles) I don't see any problems to fill it out. The only thing we should discuss with the community upfront is the long time roadmap and vision. This really depends on how many people are involved and how motivated the community is to contribute. 

If you look into our brainstroming notes we have ideas and potential for much more than the current website and report. To create this we also would need a "vision of change" or guiding principles we are gone follow and strengthen. Those can be based on the "[Open Sustainability Principles](https://report.opensustain.tech/chapters/principles.html)" we created in the last report. One could derive from the principles a comparable vision and principles based on the [LF Energy principles](https://wiki.lfenergy.org/display/HOME/LF+Energy+Guiding+Principles) but with a certain extend to Open Sustainability in general.

**Comment by Ly0n** [comment]
Here a first draft for the LF Energy Project Application: https://hackmd.io/@YhPkDVi5RJK7NY7ttj2HZQ/B13EBTaTn/edit
Feel free to edit, comment and change the existing content.

**Comment by Ly0n** [comment]
@jmertic I did some additional work today on the project proposal. The only part I'm unsure about is: 
> Provide a statement on alignment with the mission in the LF Energy charter.

I wrote here something but it is not clear from the wiki which mission statement we are talking about. Please double check :)

**Comment by jmertic** [comment]
Was just reviewing this - I think it's good. Overall the proposal looks good to me.

**Comment by Ly0n** [comment]
@jmertic @dbrownlf The proposal was submitted by me to the Technical Advisory Council of LF Energy. :partying_face:

**Comment by Ly0n** [comment]
We are accepted as member of LF Energy :partying_face:
