### ISSUE TITLE
Splitting and restructuring of the fields / topics 

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#149]
The current structure of the fields / topics has resulted in some subject areas becoming very large. This makes the list difficult to navigate. In addition, it would be interesting to better divide the subject area in the analysis to make focal points and gaps more recognizable. This structure has an significant impact on the data analysis we are doing. My good old collage @kikass13 developed the parser we are using at the moment for the list. If we would add another level to the list like field / topic / subtopic we have to change this script. A new structure also has significant on the website framework. Therefore, it would be good to find a structure that allows us to keep with a 2 level structure. 
Here are some fields that urgently need splitting and a suggestion how to split them:

- Biosphere
	* Biodiversity
	* Forest and Vegetation
	* Wildfire 
	* Biomass
	* Habitats Conservation and restoration 
	* Marine life and Fishery 
   
- Hydrosphere
     - Freshwater and Groundwater
     - Oceans
     - Coastal and Reefs

- Atmosphere
	- Atmospheric Dynamics
	- Atmospheric Chemistry
	- Clouds and Water Vapor

- Cryosphere
	- Glacier
	- Arctic and Antarctic
	- Snow and Permafrost

**Comment by Ly0n** [comment]
Yes, that is a good point. We can include such classification as special labels in the metadata. This is actually a new issue your are proposing. For the UN-SDGs we can one of the many existing open source tools: 

-  https://github.com/osdg-ai/osdg-tool
- https://github.com/dwulff/text2sdg
- https://github.com/Yingjie4Science/SDGdetector

**Comment by kikass13** [comment]
> My good old collage @kikass13 developed the parser we are using at the moment for the list. If we would add another level to the list like field / topic / subtopic we have to change this script.

I have changed some things (after reading this thread),  I am bored so what exactly do you need?

 * the script now visualizes topics -> entries + children better
 * i have added a json serialization of the underlying data to the script (will be printed into a json.txt file)

is there something specific you guys want? I dont really understand he use case ;/

**Comment by Ly0n** [comment]
@joshhopkins 
I did a complete split of the Earth Systems Field. You can find it here:
https://github.com/protontypes/open-sustainable-technology/tree/split_fields

Do you like the topics? 
I'm also considering to split further the climate science field. Dividing the projects into more topic areas makes the list much clearer. 

I also changed the headline to:
```
A directory of all active open source projects for the sustainability of climate, energy supply, biodiversity and natural resources.
```
I changed the headline because it represents now much better the headline of the story. Do you like it? Does it sound good to you?

**Comment by Ly0n** [comment]
I did the split of the climate field today:
https://github.com/protontypes/open-sustainable-technology/tree/split_fields_climate

I moved Radiative Transfer and Meteorological Observation and Forecast to the Atmosphere field.
