### ISSUE TITLE
What is the role of AI in this open source ecosystem?

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#155]
We are in the unique position of being able to quantify the application of machine learning, deep learning and artificial intelligence within sustainability. One way to do this is based on the dependencies of the open source software projects and their dependencies. Another way is NLP or simple keyword matching based on the project READMEs. 

The results of this analysis could be of interest to a very large group of people.

**Comment by dbrownlf** [comment]
LF Energy has a director of AI on board now, Alexandre Parisot, and he is doing an analysis of where AI ties into the energy ecosystem. Probably worth inviting him to one of our meetings to see where his work ties into the project.

**Comment by Ly0n** [comment]
With the dependency tree for every project from @andrew 's ecosyste.ms we can quantify the amount of AI usage sector based. I consider this a relative easy task to solve if we can find a good list of the most commonly used libraries for machine learning, deep learning, etc. For this analysis we would also need the dependencies of the dependencies.
