### ISSUE TITLE
Apply for 2023 Digital Infrastructure Insights Fund RFP

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#158]
This fund looks like it was made for us:
https://fordfoundation.forms.fm/2023-digital-infrastructure-insights-fund-rfp/forms/9724

"We aim to back the development of pertinent work that examines the convergence of open-source software and digital infrastructure with social movements focused on democracy, rights, justice, the environment and scientific research."

Deadline:
Oct 1 at 12:00am
In your local timezone (GMT +2)

Grant Amount: We seek to support proposals addressing a range of issues and different scopes that are in a ballpark between $50k – $125k for 6 - 12 months projects, managed via Open Collective (exceptions possible for 18 month-proposals)

**Comment by Ly0n** [comment]
It started today with a first draft related to this fund:
https://hackmd.io/er0EXrR1Qo-PW9EOsG_soQ

@dbrownlf @joshhopkins @andrew I have also included the names of your organizations in the draft. Any concerns about this? This would make this organisation central drivers for the next report.  We clould also finance @rockita through this fund. 

I would be very happy about any support or feedback. I will try to have a first draft ready by the next meeting on Wednesday. Since this find is aimed exactly at projects like ours, I think it is very likely that we will find support here.

**Comment by andrew** [comment]
@Ly0n no concerns on my end 👍

**Comment by dbrownlf** [comment]
Looks good to me @Ly0n. No issues on our end with listing LF Energy.
