### ISSUE TITLE
Switch from Twitter to Mastodon

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#173]
Twitter is geeting more and more inactive. In addition, the platform can no longer be regarded as a neutral communication platform. Our automation publishing new projects via the API also does not work anymore on Twitter.

The only open source solution I'm aware of that could be used as an replacement is Mastodon. We could also think about using LinkedIn as a platform. Let's create an automation for Mastodon to publish new projects we add to Open Sustainable Technology.

**Comment by andrew** [comment]
There's a github action for posting to mastodon over here: https://github.com/cbrgm/mastodon-github-action that uses https://github.com/neet/masto.js under the hood to do the actual post request.

**Comment by Ly0n** [comment]
Great! That's exactly what we need! I wonder how much we can automate in this way. In the past, I manually created the hashtags and searched for the usernames of people/organisations on Twitter that mentioned them. The posts looked like this: Project Oneliner + hashtags + usernames of contributors + repolink. The automatic creation of the posts was triggered by adding a string with "https" in it to the README.

**Comment by andrew** [comment]
@Ly0n the hardest part will be finding the mastodon usernames, either manually or automated!

**Comment by Ly0n** [comment]
The GitHub API provided a way to get the Twitter username of a GitHub user. So it might also be possible to get the Mastodon usernames from the strongest GitHub repos. I'll look into this more when I get back from holiday.

**Comment by andrew** [comment]
@Ly0n you can retrieve the social accounts with provider type `MASTODON` from the graphql api but not the rest api: https://docs.github.com/en/graphql/reference/objects#socialaccount

**Comment by Ly0n** [comment]
@andrew Than we should be able to automated everything. The hastags can be created by the topic modeling with NLP.

**Comment by Ly0n** [comment]
I created an Mastodon account for us here with an shared email address for the community: https://mastodon.social/@opensustaintech
