### ISSUE TITLE
Grist as AirTable Alternative

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#174]
In the past, we have experienced several cost traps within AirTable. Furthermore, AirTable is not open source and does not offer a good API or the ability to display logos / images that are not hosted on AirTable itself. Grist looks very promising. Evaluate Grist as an alternative to AirTable and what possibilities it offers.

**Comment by Ly0n** [comment]
How to update a table from a CSV file: https://community.getgrist.com/t/how-to-update-all-contents-of-a-table-from-a-local-remote-csv-file-using-python-api/3179

How to show images from an URL in a card view: https://docs.getgrist.com/gSscJkc5Rb1R/projects/p/2

**Comment by andrew** [comment]
https://github.com/gristlabs/grist-static looks very neat for simplified hosting too

**Comment by Ly0n** [comment]
@andrew Looks pretty much like what we need. Such an integration would perhaps also load much faster than the AirTable integration we are currently doing via an IFrame. 

I also played around with the Grist UI yesterday. Even the UX is already better or comparable to AirTable.

**Comment by Ly0n** [comment]
I integrated the new dataset into grist here: https://docs.getgrist.com/gSscJkc5Rb1R/OpenSustaintech
It is much better than AirTable and Google Docs. With 5000 rows and 10 MBs of max CSV file import the limits are also much better for us. The website does also provide 10 GB of free storage for images / logos.
Next steps:
1. Investigate the static side integrated that @andrew mentioned. 
2. Investigate the API so that we can update the spreadsheets automatically. Maybe we could also create an Python package for our dataset via the API. 
3. Investigate the possibility to show all organisation logos in the spreadsheets: [docs.getgrist.com/gSscJkc5Rb1R/projects/p/2](https://docs.getgrist.com/gSscJkc5Rb1R/projects/p/2)
4. Investigate the widgets function and other data analytics function that Grist provide.
5. Create some social media posts how awesome Grist is and the release of the new datasets as a spreadsheet.
