### ISSUE TITLE
Organizational Distribution Score

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#176]
In his presentation at the Open Technology for Sustainability Day 2023, @dbrownlf proposed an organizational distribution score that shows the extent to which contributors of a repository belong to different organizations. 

This might also be very interesting for @andrew and ecosyste.ms.

**Comment by andrew** [comment]
I did some work a couple years back for Protocol Labs to work out which organizations a github user belonged to based on if they had performed actions (using the events api) on a repository that only an owner of an org could do (merging a PR, pushing directly to the main branch etc), so was able to then group contributors by org, the code is open source as part of https://github.com/ipfs-shipyard/ecosystem-dashboard so could be reused for that. 

We also have the email addresses in the commits, which could be grouped by domain as a lighter weight option.

**Comment by andrew** [comment]
I deployed a little test for grouping by email domain, it's not great but it does kinda work: https://ost.ecosyste.ms/projects/20003

<img width="361" alt="Screenshot 2023-10-10 at 17 13 38" src="https://github.com/protontypes/open-sustainable-technology/assets/1060/0a1fec36-a693-445c-b270-656ed6d91a32">
