### ISSUE TITLE
Announcement of Open Sustainable Technology joined LF Energy.

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#180]
The projects was accepted as member of LF Energy in the incubation stage. :partying_face:  
To announce that publicly we can use existing text blogs from the LF Energy application document and the grant documents:

https://hackmd.io/@YhPkDVi5RJK7NY7ttj2HZQ/B13EBTaTn/edit
https://hackmd.io/@YhPkDVi5RJK7NY7ttj2HZQ/SyGHj1j0n/edit
https://hackmd.io/@YhPkDVi5RJK7NY7ttj2HZQ/HkI-Cxgx6/edit

The blog post can be released on OpenSustain.tech and the LF Energy Website. The blog post should reflect our long-term goals and perhaps include a small roadmap.

The blog post can also been used to make a community call to get more members excited about the project. What do you think about this?

@dbrownlf @andrew @joshhopkins @jmertic 

The same blog post could also been used to announce the collaboration with Ecosyste.ms. But I think it makes sense to publish this in another blog post. Otherwise it will be just too much for one article.

**Comment by Ly0n** [comment]
@dbrownlf I filled everything out. The only thing that we need to clarify is the license of the website since it is not a OSI Approved Licenses.

**Comment by dbrownlf** [comment]
Thanks @Ly0n! Looks good on my end. I've sent the logo details to design so they can get started on it. I saw the note in Slack about the license and will let John weigh in there.
