### ISSUE TITLE
Future of the Education Dataset

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#197]
The current [Education](https://opensustain.tech/education/) page was curated separately from the core data set. Unfortunately, there are not enough high-quality open source projects in this area that have been maintained over a long period of time. These projects are also not included in the datamining and analyses. One possibility would be to list all these projects on the core README file under a Education field. This would have several advantages:

1. education projects are not so easily lost on the website and can also be seen directly on the GitHub landing page.
2. education projects are part of the analysis and datamining.
3. education projects are easier to integrate into the spreadsheet.

I created this issue to discuss possible ways to deal with this part of the projects in the future. What is your opinien? @andrew @jmertic @joshhopkins @dbrownlf

**Comment by jmertic** [comment]
I guess my question is if quality was the only reason why this isn't in the main data set, or are there other historical reasons?

I know if we were to use the landscape, this is easy to add with a new category.

**Comment by Ly0n** [comment]
The reason why it was not included in the original dataset is to make it better visible for people looking for an entry point. Hiding the education projects in all the existing topics would make it hard for newbies to find them. 

And please don't make it always about the landscape. I understand that you are pusing very hard that the landscape is been used within this project.

**Comment by jmertic** [comment]
Hi @Ly0n - I apologize if you took my comments as pushing the landscape. I was illustrating how the question could be addressed with an existing tool that I have familiarity with, but if there is a desire to have discussions without tooling specifically, I'm happy to do that.
