### ISSUE TITLE
Global weather forecasting - GraphCast

### ISSUE THREAD

**Issue by fkromer** [protontypes/open-sustainable-technology#202]
https://github.com/google-deepmind/graphcast could be interesting for you @Ly0n

**Comment by Ly0n** [comment]
Thanks for pointing this out! I read about it but didn't see that it was open source. Do you want to add it? @fkromer

**Comment by Ly0n** [comment]
@fkromer I' do have allmost all commits on this project ^^. I would be really happy to see you on the contributors side :).
