### ISSUE TITLE
TimeGPT

### ISSUE THREAD

**Issue by fkromer** [protontypes/open-sustainable-technology#222]
I know this project is not about advertising non open source products. However it's worth to mention... at least in the issues:

Recently I've watched some videos ([Time GPT Live Demo](https://www.youtube.com/watch?v=HZh_X5ZHqq8), [TimeGPT Launch | Max Mergenthaler Introduces TimeGPT](https://www.youtube.com/watch?v=cJZVguJY1fA), ) about [TimeGPT](https://www.nixtla.io/timegpt). Here is the [Medium release post "TimeGPT: The Frist Foundation Model for Time Series Forecasting"](https://towardsdatascience.com/timegpt-the-first-foundation-model-for-time-series-forecasting-bf0a75e63b3a). The [ecosystem is open source](https://www.nixtla.io/open-source). The pre-trained model is not of course :) There is a Python SDK for connecting to the pre-trained TimeGPT model via Python called [nixtla](https://github.com/Nixtla/nixtla). The model can give you forecasting and anomaly detection predictions without the need for training a model yourself. The data (100B data points) which was used for training the model does not include weather data (domains included: finance, electricity, web traffic, retail, tourism, IoT, healthcare, transport, economics). I'm pretty sure this product will have some significant impact on the time series forecasting / anomaly detection domain.

The model could be re-trained with weather data (or whatever else could be of interest for sustain tech as well) and speed up sustain tech research significantly.

**Comment by Ly0n** [comment]
The contribution guidelines do not determine that the entire project is open source, but only larger parts of it. So from that perspective, that's fine. What is really missing is an open source application in the field of sustainability or the written goal for sustainability purposes. 

Thanks for the links anyway. Very interesting technology. The whole area is developing so quickly that it often seems difficult to check all the possibilities.

Within this project we also have very good use cases for LLMs and NLP: #145
