### ISSUE TITLE
Weather forcasts: Graphcast, Metnet3

### ISSUE THREAD

**Issue by lukestanley** [protontypes/open-sustainable-technology#296]
Apparently this is SOTA weather forecasting:
https://github.com/google-deepmind/graphcast

Google's Deepmind also did short term estimation research, there is a 3rd party implementation:
https://github.com/lucidrains/metnet3-pytorch

**Comment by Ly0n** [comment]
Thanks @lukestanley. Graphcast is already listed but metnet3 is missing. I would be delighted to receive a PR from you!
