### ISSUE TITLE
Add open sustainable business / extend contribution area

### ISSUE THREAD

**Issue by tjarkdoering** [protontypes/open-sustainable-technology#36]
With the website in mind and and goals extending beyond the list itself, contribution becomes a broader term.
Contribution (within our cause) can be basically anything that is aiming at sustainability and open source.

I would suggest extending the contribution guide and making a new category, sth. like "Open Sustainable Business".
To have an area to gather events like hackathons and similar events. To make contributing in any sense more accessible.

**Comment by Ly0n** [comment]
Please make a tweet for every organization that we add to the business section.
