### ISSUE TITLE
opensustain.tech seal of approval

### ISSUE THREAD

**Issue by tjarkdoering** [protontypes/open-sustainable-technology#42]
To have a badge for projects to add to their websites/READMEs to show that they are on the list.

Contribute/Propose by adding/PRing to the [logos Repo](https://github.com/protontypes/logos).
Here are the ideas so far.

[![](https://badgen.net/badge/OpenSustain/Tech/009485?icon=https://raw.githubusercontent.com/protontypes/logos/32edd2e4df564416690b75cd97ce4f341b665775/opensustain_plain_dark.svg)](https://opensustain.tech/)

![](https://badgen.net/badge/OpenSustain/Tech/009485?icon=https://raw.githubusercontent.com/protontypes/logos/068416c3bead678220fd57364fd1756cfd6f365a/opensustain_plain_bw.svg)

**Comment by tjarkdoering** [comment]
https://badgen.net/

https://shields.io/

**Comment by tjarkdoering** [comment]
Here some proposals:

![](https://badgen.net/badge/:subject/OpenSustainTech/?icon=https://raw.githubusercontent.com/protontypes/logos/master/simple_earth_color_bright.svg&label)


![](https://badgen.net/badge/:subject/OpenSustainTech/?icon=https://raw.githubusercontent.com/protontypes/logos/master/simple_earth_color.svg&label)


![](https://badgen.net/badge/:subject/OpenSustainTech/?icon=https://raw.githubusercontent.com/protontypes/logos/master/simple_earth_bw.svg&label)

**Comment by elaristi** [comment]
Nice! I like the second one.

**Comment by Ly0n** [comment]
![](https://badgen.net/badge/:subject/OpenSustain%2ETech/?icon=https://raw.githubusercontent.com/protontypes/logos/master/simple_earth_color.svg&label)

I found a way to add the dot.

**Comment by tjarkdoering** [comment]
Nice, thanks.
I think the lines need to be a little thicker. And it doesn't look exactly round.

**Comment by tjarkdoering** [comment]
What about those:

![](https://badgen.net/badge/:subject/OpenSustain%2ETech/?icon=https://raw.githubusercontent.com/protontypes/logos/master/simple_earth_color.svg&label)

![](https://badgen.net/badge/:subject/OpenSustain%2ETech/?icon=https://raw.githubusercontent.com/protontypes/logos/master/simple_earth_transp_outline.svg&label)

![](https://badgen.net/badge/:subject/OpenSustain%2ETech/?icon=https://raw.githubusercontent.com/protontypes/logos/master/simple_earth_transp.svg&label)

**Comment by elaristi** [comment]
All of them are cool but I like the first one better :)
