### ISSUE TITLE
Add Scheffler Reflector (Parabolic Concentrated Solar Energy)

### ISSUE THREAD

**Issue by maltfield** [protontypes/open-sustainable-technology#429]
This is a request to add links to the Scheffler Solar Concentrator

## Why?

The Scheffler Solar Concetrator is an open hardware design for residential and industrial usage to collect solar energy from the sun for heating purposes.

Originally developed in Germany, the Scheffler technology has been used in many countries including India, Afghanistan, France, Spain, Switzerland, Mexcio, the USA, etc.

In India, for example, several Ashrams use this technology to feed tens of thousands of people every day using only the renewable energy from the sun.

Here are some videos showing this technology in-use:
1. https://www.youtube-nocookie.com/embed/wFRO4PlkrIo
2. https://www.youtube-nocookie.com/embed/kv9RZXGDHE4
3. https://www.youtube-nocookie.com/embed/kDurdi_-87k?t=37s

You can find the designs for building it on the [Solare Brücke e.V.](http://www.solare-bruecke.org/) website:

 * http://www.solare-bruecke.org/Bauanleitungen/2-7-qm-manual-juli-2010.pdf

**Comment by Ly0n** [comment]
Thanks @maltfield for the tip. A fantastic project. 

The documentation is quite old and there is no licence. Have you ever seen a similar project with an open source licence and an active community? 

Unfortunately, this project shows some problems that many open hardware developments have. Please don't get me wrong. I think these projects are really fantastic, but I also know from personal experience how difficult it is to build on such projects when there is no active community/forums to share ideas and experiences. I just want to understand why it is often so difficult to maintain such projects in the long term at the hardware level. Imagine an active community around the projects that would have developed the technology further based on the experiences of the last 10 years and could now provide support around these developments, as is the case with many open source projects. 

I see huge potential in such developments and just don't understand why there are so few open hardware solutions with strong communities and possibly even entrepreneurial success in sustainable technology.

**Comment by maltfield** [comment]
I think the Scheffler project is by far the best and most documented open hardware parabolic solar concentrator with the most wide-spread builds in the world.

Perhaps you can email them to ask for their license information?

> I just want to understand why it is often so difficult to maintain such projects in the long term at the hardware level.

My guess: hardware iteration is too costly to be maintained in the long-term

**Comment by Ly0n** [comment]
As long as they don't make the documentation and available under an open hardware licence or CC, it's not open hardware. I'm sorry to be so picky here. We have to draw the line here, because from a legal point of view, the documentation of the Scheffler solar concentrator cannot be further improved by a community approach.

**Comment by maltfield** [comment]
Lots of orgs don't know what a license is. In the past, I have successfully asked several orgs and personal blogs about their licensing. The result of some quick back-and-forth was they updated their websites to indicate that all of their work was released under CC BY-SA (per my usual suggestion).

Not only does it not hurt to ask, but by asking you can help the entire world -- because you can go from a legally ambiguous situation to them licensing all their content as libre.

**Comment by Ly0n** [comment]
> I have successfully asked several orgs and personal blogs about their licensing. 

I do the same. It sometimes works like here:
https://github.com/Plant-for-the-Planet-org/FireAlert/issues/134

The problem with the Scheffler Reflector is that it does not fit into our Contributing Guide. We only list active, open source projects that are still been maintained. For some very good projects we allow listing without a repository, but this is really an exception.

**Comment by Ly0n** [comment]
I have to admit that I would also like to list this document. It doesn't work with the current workflow because all our analytics and are mostly based on repositories. Collecting PDFs and other documents is on the roadmap but we would need a different database for that.

What we could do is add the whole thing to the education section inbetween.

**Comment by maltfield** [comment]
Scheffler has worked with companies all over the world to take this technology and use it to create businesses.

Currently, businesses *are* actively building Scheffler reflector tech. And they've taken the designs and improved them (eg an Indian company modified the designs to make a 16 sq meter dish).

So addressing the two issues:

## 1. Licensing

I can't find a specific license on their website, but--in practice--they appear to be encouraging open use & modification, including for commercial purposes

## 2. Currently Active

There are issues in the accessibility of the information (ie the active contributions are being done offline or otherwise in private communications such as emails), but the fact that Scheffler tech is being used by companies that are actively building and improving the designs. This is activity.

**Comment by Ly0n** [comment]
> That's unfortunate. Most libre hardware projects will not use git. That doesn't mean they're not libre hardware; they just prefer other workflows & tools.

Yes, that's true. Git is not very popular in the hardware world. This is perhaps one of the reasons why it is so difficult for people in this field to collaborate on documentation and design files. Most mechanical engineers do not have version control for CAD files, which makes collaboration in this area very difficult. Unfortunately, there is also a lack of open standards between different CAD programs for the exchange of parameterised drawings. 

In the electronics world, on the other hand, things look a little better, and we also have some good projects on OpenSustain.tech.

Fortunately, there are a few examples that show how it can be done like this here:
https://github.com/PlanktoScope/PlanktoScope
