### ISSUE TITLE
 Inactive Calendar Display on Website

### ISSUE THREAD

**Issue by lappemic** [protontypes/open-sustainable-technology#682]
I've noticed that the calendar on the OpenSustain.tech website is currently displayed but actually is empty. This might unintentionally give new visitors the impression that the community is inactive, potentially hindering them from engaging or contributing.

**Observations:**
- The calendar shows no upcoming events.
- There appears to be no historical data present either.

**Suggestion:**
It might be better to deactivate or hide the calendar on the website until there are events to display. This could help maintain a more active and engaging image for new visitors.

**Comment by Ly0n** [comment]
Yes, this is a very good point you are bringing up here. At the beginning of the projects we had completely open and public community meeting. Recently, however, we have been concentrating on the internal 2-weekly meetings with the core members for time reasons. 

As we want to further grow the community and integrate more people in the project we are gone kick-off mutliple community workshop for new members to join that are focusing an two areas:

1. Data Analysis and Data Mining (This would also include the clustering we are currently doing) 
2. OpenClimate.fund. --> Distributing 100x100€ to projects listed in the dataset. 

When we have the personal meeting on Monday we can discuss the organisational part of this.

**Comment by Ly0n** [comment]
I have now added the two public workshops to the calendar. The calendar now also uses the community email address opensustaintech@gmail.com. https://github.com/protontypes/open-sustainable-technology/commit/b9c2ef91259b649dacb565c46d181453e3b6e559
