### ISSUE TITLE
Create a Database or Spreadsheet out of the List

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#70]
Hey @tjarkdoering @elaristi,

here a simple suggestion how we can create a solid spreadsheet or database out of OpenSustain.tech
https://excalidraw.com/#room=95d13deb482ee2e5039c,kzSqbuh5eHSuJ-29QeuFMw
What is your opinion?

**Comment by tjarkdoering** [comment]
I like it. 

https://github.com/secretGeek/AwesomeCSV

**Comment by KKulma** [comment]
hi there, has there been any progress on this issue since March last year? I'd be interested in looking into it

**Comment by Ly0n** [comment]
Hi @KKulma.
There have been some developments here, but in a different repo: https://github.com/protontypes/AwesomeCure

In it you will find the generated CSV files on projects and organizations. The notebooks for the generation of the CSV files and for the subsequent analysis are also included. Everything is unfortunately still very prototypical, but should work on your machine. At the moment we are in the middle of creating the report, which we want to publish in about 2 months. If you are interested in participating you are very welcome. More information can be found here:
https://opensustain.tech/blog/impact_and_potential_of_open_source_on_climate_technology/

If you just want to browse the database here an AirTable upload of the CSV files:
https://airtable.com/shr9we419r2TkpLkc
