### ISSUE TITLE
Reorder Energy System Assessment Section

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#74]
https://github.com/protontypes/open-sustainable-technology/pull/73
@danielhuppmann 
> Beyond the scope of this PR, but there seems to be a bit of confusion between the "Modeling" section and the "Analysis" section - many of the entries in "Analysis" are really modelling frameworks (e.g., PyPSA, oemof, matpower, POMATO), whereas pyam and the Open Energy Platform (and possibly others in that section) are tools for analysis-and-visualization packages/tools (but not for creating the scenario results). A bit of a review and structuring/tagging might be helpful...

**Comment by danielhuppmann** [comment]
It's a complex thing to do properly... It would be useful to give this a bit more structure beyond the section header, e.g., programming language(s), sectoral/temporal coverage (where this makes sense), ...

See two projects that tried to do something similar with categorizing models or modeling frameworks...
 - https://wiki.openmod-initiative.org/wiki/Open_Models
 - https://www.iamcdocumentation.eu/index.php/IAMC_wiki

**Comment by Ly0n** [comment]
I simply removed the subsections to make the catalogs flatter. This makes it less confusing from my point of view
