### ISSUE TITLE
Add Home Assistant Add-ons 

### ISSUE THREAD

**Issue by Ly0n** [protontypes/open-sustainable-technology#748]
Our dataset is missing several Home Assistant extensions that we could include in the new [Building Energy Monitoring](https://opensustain.tech/#building-energy-monitoring) section and others. Here are some examples we would like to list. Some projects may already be listed: 

https://github.com/klaasnicolaas/home-assistant-glow 
https://github.com/KartoffelToby/better_thermostat
https://github.com/StephanJoubert/home_assistant_solarman 
https://github.com/flixlix/power-flow-card-plus
https://github.com/MindFreeze/ha-sankey-chart
https://github.com/Pirate-Weather/pirate-weather-ha 
https://github.com/davidusb-geek/emhass
https://github.com/reptilex/tesla-style-solar-power-card
https://github.com/FL550/dwd_weather
https://github.com/CJNE/ha-myenergi
https://github.com/flixlix/energy-flow-card-plus
https://github.com/hif2k1/battery_sim
https://github.com/radical-squared/aquatemp
https://github.com/macxq/foxess-ha
https://github.com/jmcollin78/solar_optimizer
https://github.com/patman15/BMS_BLE-HA
https://github.com/klaasnicolaas/home-assistant-glow
https://github.com/fsaris/home-assistant-zonneplan-one
https://github.com/JensenNick/huawei_solar_pees
https://github.com/wlcrs/huawei_solar
https://github.com/ksheumaker/homeassistant-apsystems_ecur
https://github.com/tolwi/hassio-ecoflow-cloud
https://github.com/kamaradclimber/rte-ecowatt
https://github.com/KartoffelToby/better-thermostat-ui-card
https://github.com/germainlefebvre4/libtado

Do you know of more projects that are relevant for environmental sustainability as part of Home Assistant?

**Comment by VIKTORVAV99** [comment]
There is also: https://github.com/jpbede/aioelectricitymaps which is added as a core integration in Home Assistant.

**Comment by Ly0n** [comment]
Thanks for the tip! @VIKTORVAV99 Do you want to add this to the dataset? If not, I will do it next week.

**Comment by VIKTORVAV99** [comment]
I'm planning on adding Electricity Maps (the data provider) so I can take a look at adding the add-on as well!

**Comment by Ly0n** [comment]
@VIKTORVAV99 Electricity Maps is one of the most popular projects in this entire open source ecosystem and is therefore already listed. :stuck_out_tongue_winking_eye:

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 Electricity Maps is one of the most popular projects in this entire open source ecosystem and is therefore already listed. :stuck_out_tongue_winking_eye:

Oh nice! I didn't see it when I skimmed through them all but happy to hear that!

**Comment by Ly0n** [comment]
All project reviewed.
