### ISSUE TITLE
Website looks out sync with docs

### ISSUE THREAD

**Issue by JarnoRFB** [protontypes/open-sustainable-technology#77]
Hey, I just checked https://opensustain.tech/contributing/ and found that bullet points in the `Contribute to the list` section are not being correctly rendered. When I wanted to check what the reason might be I also found that the document under `docs/contribution.md` has slightly different content, so something seems to be amiss. Unfortunately I couldn't find out much more, but hopefully it helps to identify the issue.

**Comment by Ly0n** [comment]
Thanks @JarnoRFB. The problem was the mkdocs template misinterpreting the markdown file. Does it look better now for you?

**Comment by JarnoRFB** [comment]
Superb. The missing newline again :D
