### ISSUE TITLE
Matter protocol

### ISSUE THREAD

**Issue by fkromer** [protontypes/open-sustainable-technology#788]
The Matter protocol https://csa-iot.org/all-solutions/matter/ is the current de-facto standard for smart sustainable homes.

Some member companies like Schneider Electric are pushing forward topics like „net zero homes“ already. The current protocol version 1.3 https://www.theverge.com/2024/5/8/24151664/matter-smarthome-standard-spec-1dot3-released-device-types-features supports corresponding device types https://handbook.buildwithmatter.com/howitworks/devicetypes/ like

- power source,
- device energy management,
- heating/cooling unit,
- thermostat,
- refrigerator,
- air conditioner,
- … (other energy hungry devices),
- Electrical Vehicle Supply Equipment.

Future protocol versions will include device types for other energy related devices.

**Comment by Ly0n** [comment]
Thanks @fkromer for the hint. I agree that this protocol is interesting and can be used for sustainable use-cases. Unfortunately, there is no clear sustainability statement on the website and in the documents you have shared. I would need a repository with a clear sustainability use cases.
