### ISSUE TITLE
match with conda-forge

### ISSUE THREAD

**Issue by ReimarBauer** [protontypes/open-sustainable-technology#91]
It would be interesting to see which of this Software is in the [conda-forge](https://github.com/conda-forge/ )repository so we could get it easily installed by the mamba installer.

Are there plans to map this information?

**Comment by Ly0n** [comment]
We planned to get metadata from each project via the GitHub API in the near future. Since the list conforms to the "Awesome" standard, this would be possible with a simple script. @kikass13 already provides a simple Python script to convert the list to a dict. 
https://github.com/kikass13/awesome2py

From this point we could also parse information to use it with the conda-forger.

**Comment by kikass13** [comment]
Oh gawd, what have I done. :O

**Comment by andrew** [comment]
@ReimarBauer better late than never: 

- https://anaconda.org/anaconda/libnetcdf
- https://anaconda.org/anaconda/netcdf4
- https://anaconda.org/conda-forge/andes
- https://anaconda.org/conda-forge/aospy
- https://anaconda.org/conda-forge/argopy
- https://anaconda.org/conda-forge/atlite
- https://anaconda.org/conda-forge/calliope
- https://anaconda.org/conda-forge/capytaine
- https://anaconda.org/conda-forge/catalystcoop.pudl
- https://anaconda.org/conda-forge/cdsapi
- https://anaconda.org/conda-forge/cellpy
- https://anaconda.org/conda-forge/cfgrib
- https://anaconda.org/conda-forge/climlab
- https://anaconda.org/conda-forge/climpred
- https://anaconda.org/conda-forge/clisops
- https://anaconda.org/conda-forge/codecarbon
- https://anaconda.org/conda-forge/codecarbon-dev
- https://anaconda.org/conda-forge/codecarbon-test
- https://anaconda.org/conda-forge/codecarbon-viz
- https://anaconda.org/conda-forge/deepforest
- https://anaconda.org/conda-forge/detectree
- https://anaconda.org/conda-forge/e3sm_diags
- https://anaconda.org/conda-forge/echopype
- https://anaconda.org/conda-forge/entsoe-py
- https://anaconda.org/conda-forge/fine
- https://anaconda.org/conda-forge/flopy
- https://anaconda.org/conda-forge/geoschem-gcpy
- https://anaconda.org/conda-forge/glaes
- https://anaconda.org/conda-forge/gsee
- https://anaconda.org/conda-forge/hydrofunctions
- https://anaconda.org/conda-forge/icclim
- https://anaconda.org/conda-forge/icepyx
- https://anaconda.org/conda-forge/intake-esm
- https://anaconda.org/conda-forge/lakepy
- https://anaconda.org/conda-forge/landlab
- https://anaconda.org/conda-forge/libnetcdf
- https://anaconda.org/conda-forge/message-ix
- https://anaconda.org/conda-forge/metpy
- https://anaconda.org/conda-forge/metsim
- https://anaconda.org/conda-forge/mocsy
- https://anaconda.org/conda-forge/modflow6
- https://anaconda.org/conda-forge/mpas-analysis
- https://anaconda.org/conda-forge/mss
- https://anaconda.org/conda-forge/natcap.invest
- https://anaconda.org/conda-forge/netcdf-fortran
- https://anaconda.org/conda-forge/netcdf4
- https://anaconda.org/conda-forge/noaa-coops
- https://anaconda.org/conda-forge/oceanspy
- https://anaconda.org/conda-forge/openmdao
- https://anaconda.org/conda-forge/parcels
- https://anaconda.org/conda-forge/pastas
- https://anaconda.org/conda-forge/pcraster
- https://anaconda.org/conda-forge/podaacpy
- https://anaconda.org/conda-forge/pvcaptest
- https://anaconda.org/conda-forge/pvlib
- https://anaconda.org/conda-forge/pvlib-python
- https://anaconda.org/conda-forge/pyam
- https://anaconda.org/conda-forge/pybamm
- https://anaconda.org/conda-forge/pycoal
- https://anaconda.org/conda-forge/pyfor
- https://anaconda.org/conda-forge/pylandstats
- https://anaconda.org/conda-forge/pymagicc
- https://anaconda.org/conda-forge/pymt
- https://anaconda.org/conda-forge/pynco
- https://anaconda.org/conda-forge/pypsa
- https://anaconda.org/conda-forge/pysheds
- https://anaconda.org/conda-forge/pysolar
- https://anaconda.org/conda-forge/pysteps
- https://anaconda.org/conda-forge/r-aqp
- https://anaconda.org/conda-forge/r-biodivmapr
- https://anaconda.org/conda-forge/r-downscaler
- https://anaconda.org/conda-forge/r-landscapemetrics
- https://anaconda.org/conda-forge/r-loader
- https://anaconda.org/conda-forge/r-loader.2nc
- https://anaconda.org/conda-forge/r-metr
- https://anaconda.org/conda-forge/r-oce
- https://anaconda.org/conda-forge/r-openair
- https://anaconda.org/conda-forge/r-palmerpenguins
- https://anaconda.org/conda-forge/r-r2dii.analysis
- https://anaconda.org/conda-forge/r-rebird
- https://anaconda.org/conda-forge/r-redlistr
- https://anaconda.org/conda-forge/r-rgbif
- https://anaconda.org/conda-forge/r-robis
- https://anaconda.org/conda-forge/r-rredlist
- https://anaconda.org/conda-forge/r-sits
- https://anaconda.org/conda-forge/r-spatialeco
- https://anaconda.org/conda-forge/r-spei
- https://anaconda.org/conda-forge/r-spocc
- https://anaconda.org/conda-forge/r-wdpar
- https://anaconda.org/conda-forge/radiant-mlhub
- https://anaconda.org/conda-forge/raven-wps
- https://anaconda.org/conda-forge/rivgraph
- https://anaconda.org/conda-forge/sentinelhub
- https://anaconda.org/conda-forge/sentinelsat
- https://anaconda.org/conda-forge/siphon
- https://anaconda.org/conda-forge/stormevents
- https://anaconda.org/conda-forge/switch_model
- https://anaconda.org/conda-forge/tespy
- https://anaconda.org/conda-forge/thermo
- https://anaconda.org/conda-forge/tsam
- https://anaconda.org/conda-forge/usgs
- https://anaconda.org/conda-forge/wetterdienst
- https://anaconda.org/conda-forge/whitebox_tools
- https://anaconda.org/conda-forge/windpowerlib
- https://anaconda.org/conda-forge/windrose
- https://anaconda.org/conda-forge/windse
- https://anaconda.org/conda-forge/wntr
- https://anaconda.org/conda-forge/wrf-python
- https://anaconda.org/conda-forge/xclim
- https://anaconda.org/conda-forge/xgcm
- https://anaconda.org/conda-forge/xskillscore

Aggregated from https://summary.ecosyste.ms/collections/1
